version: '3'
services:
    api:
        env_file:
            - .env
        build: .
        ports:
            - 80:80
        restart: always
        # volumes:
            #    - ${PATH_LOG}:/app/log
        deploy:
          resources:
             limits:     
                memory: 512m
                cpus: "2"