version: '3'
services:
    api:
        env_file:
            - .env
        build: .
        ports:
            - ${PORT}:80
        restart: always
        volumes:
               - ${PATH_LOG}:/app/log
        deploy:
          resources:
             limits:     
                memory: ${MEM}
                cpus: "${CPUs}"
    mlflow-db:
        image: postgres:10.5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            restart: always
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:${DB_PORT}

    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - mlflow-db
        command: mlflow-db:${DB_PORT}   

    mlflow-server:
        build: ./mlflow
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:${DB_PORT}/${POSTGRES_DB}
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
        restart: always
        depends_on:
            - waitfordb
        volumes:
               - ".${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
    mlflow-ui:
        build: ./mlflow
        ports:
            - ${UI_PORT}:${UI_PORT}
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:${DB_PORT}/${POSTGRES_DB}
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
        restart: always
        depends_on:
            - mlflow-server
        volumes:
                - ".${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
        entrypoint: ./start_ui.sh
# volumes:
#     mlflow-db:
#         driver: local