version: '3'
services:
    postgresql:
        image: postgres:10.5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: mlflow-db
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            restart: always
        volumes:
            - mlflow-db:/var/lib/postgresql/data
        ports:
            - ${IP_ADDRESS}:${DB_PORT}:${DB_PORT}

    waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            - postgresql
        command: postgresql:${DB_PORT}   

    mlflow-server:
        build: .
        ports:
            - ${IP_ADDRESS}:${SERVER_PORT}:${SERVER_PORT}
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:${DB_PORT}/mlflow-db
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
        restart: always
        depends_on:
            - waitfordb
        volumes:
               - "${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
    mlflow-ui:
        build: .
        ports:
            - ${IP_ADDRESS}:${UI_PORT}:${UI_PORT}
        environment:
            DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:${DB_PORT}/mlflow-db
            MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME}"
            MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD}"
            MLFLOW_ARTIFACT_ROOT: "${MLFLOW_ARTIFACT_ROOT}"
        restart: always
        depends_on:
            - mlflow-server
        volumes:
                - "${MLFLOW_ARTIFACT_ROOT}:${MLFLOW_ARTIFACT_ROOT}"
        entrypoint: ./start_ui.sh

volumes:
    mlflow-db:
        driver: local